<?php

// -----------------------------------------
// semplice
// admin/atts/customize/navigations.php
// -----------------------------------------

$navigations = array(
	'tabs' => array(
		'styling' => array(
			'general_options' => array(
				'title' => 'Name your Navigation',
				'break' => '1,2',
				'hide-title' => false,
				'class' => 'cb-hidden',
				'name' => array(
					'title'				=> 'Name',
					'hide-title'		=> true,
					'size'				=> 'span4',
					'data-input-type'	=> 'input-text',
					'default'			=> '',
					'placeholder'		=> 'My Nav',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'navigations',
					'data-target'		=> 'none',
				),
				'default' => array(
					'data-input-type' 	=> 'button',
					'title'		 		=> 'Make Default',
					'button-title'		=> 'Default',
					'help'				=> 'If selected, this nav will be used for all pages or projects without an individual assigned nav.',
					'size'		 		=> 'span2',
					'class'				=> 'semplice-button navbar-default white-button',
				),
				'preview_bg' => array(
					'title'			=> 'Preview BG Color',
					'help'		=> 'Change the background color for the nav preview to reflect your site design.',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'data-target'	=> '.customize-content',
					'default'		=> '#ffffff',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'data-css-attribute'=> 'background-color',
					'data-picker'		=> 'navigations',
				),
			),
			'logo_options' => array(
				'title' => 'Logo Options',
				'break' => '1,2,2,2,2,2,1,1',
				'style-class' => 'navbar-logo-options',
				'hide-title' => false,
				'logo_type' => array(
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Logo Type',
					'size'		 				=> 'span4',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'navigations',
					'data-visibility-switch' 	=> true,
					'data-visibility-values' 	=> 'img,text',
					'data-visibility-prefix'	=> 'ov-logo',
					'default' 	 				=> 'text',
					'style-class'				=> 'cb-hidden',
					'switch-values' => array(
						'text'  	=> 'Textlogo',
						'img'	 	=> 'Image',
					),
				),
				'logo_text' => array(
					'title'				=> 'Textlogo',
					'size'				=> 'span2',
					'data-input-type'	=> 'input-text',
					'default'			=> get_bloginfo('name'),
					'placeholder'		=> 'My Textlogo',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'navigations',
					'style-class'		=> 'ov-logo-text cb-hidden',
				),
				'logo_text_color' => array(
					'title'			=> 'Color',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'data-target'	=> '.logo a',
					'default'		=> 'transparent',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'data-css-attribute'=> 'color',
					'style-class'		=> 'ov-logo-text cb-hidden',
					'data-picker'		=> 'navigations',
				),
				'logo_text_font_family' => array(
					'title'				=> 'Font Family',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-fonts',
					'data-target'		=> '.logo a',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'style-class'		=> 'ov-logo-text cb-hidden',
					'select-box-values' => $fonts,
				),
				'logo_text_text_transform' => array(
					'title'				=> 'Text Transform',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'default'			=> 'none',
					'style-class'		=> 'ov-logo-text cb-hidden',
					'data-target'		=> '.logo a',
					'data-css-attribute'=> 'text-transform',
					'select-box-values' => array(
						'none'			=> 'None',
						'uppercase'		=> 'Uppercase',
					),
				),
				'logo_text_fontsize' => array(
					'title'				=> 'Fontsize',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'style-class'		=> 'ov-logo-text is-cb-option',
					'data-css-attribute'=> 'font-size',
					'data-target'		=> '.logo a',
					'data-has-unit'		=> true,
					'default'			=> 22,
					'min'				=> 0,
					'max'				=> 9999,
					'data-range-slider' => 'navigations',
					'data-cb-option'	=> true,
				),
				'logo_text_letter_spacing' => array(
					'title'				=> 'Letter Spacing',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 9999,
					'style-class'		=> 'ov-logo-text cb-hidden',
					'data-target'		=> '.logo a',
					'data-css-attribute'=> 'letter-spacing',
					'data-divider'		=> 10,
					'data-has-unit'		=> true,
					'data-negative' 	=> true,
					'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
					'data-range-slider' => 'navigations',
				),
				'logo_img' => array(
					'title'				=> 'Upload',
					'help'				=> 'If your server won\'t allow you to upload an SVG for security reasons, please use the \'SVG Code\' field below.',
					'size'				=> 'span2',
					'data-input-type'	=> 'admin-image-upload',
					'data-target'		=> '.content-block',
					'default'			=> '',
					'class'				=> 'admin-listen-handler',
					'style-class'   	=> 'ov-logo-img ce-upload-small hide-unsplash cb-hidden',
					'data-handler'		=> 'navigations',
					'data-upload'		=> 'logoImg',
				),
				'logo_img_width' => array(
					'title'				=> 'Width',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 100,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'data-css-attribute'=> 'width',
					'data-target'		=> '.logo img, .logo svg',
					'style-class'		=> 'ov-logo-img is-cb-option',
					'data-range-slider' => 'navigations',
					'data-cb-option'	=> true,
				),
				'logo_margin' => array(
					'title'				=> 'Logo Ver Margin',
					'size'				=> 'span2',
					'help'				=> 'Adjust the vertical alignment of your logo within the navbar.',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'navigations',
					'data-css-attribute'=> 'margin-top',
					'data-target'		=> '.logo',
					'data-has-unit'		=> true,
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 9999,
					'data-negative'		=> true,
					'data-range-slider' => 'navigations',
					'data-cb-option'	=> true,
					'style-class'		=> 'logo-margin is-cb-option',
				),
				'logo_padding' => array(
					'title'				=> 'Logo Hor Padding',
					'size'				=> 'span2',
					'help'				=> 'Change the horizontal logo padding to define the distance from your logo to the menu items on both sides.',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'navigations',
					'data-css-attribute'=> 'padding',
					'data-target'		=> '.logo',
					'data-has-unit'		=> true,
					'default'			=> 40,
					'min'				=> 0,
					'max'				=> 9999,
					'data-range-slider' => 'navigations',
					'data-cb-option'	=> true,
					'style-class'		=> 'navbar-logo-padding is-cb-option',
				),
				'logo_svg' => array(
					'title'				=> 'SVG Code',
					'size'				=> 'span4',
					'help'				=> 'Please note: The logo image option above will override the SVG. To see your SVG, don\'t upload a logo above.',
					'data-input-type'	=> 'codemirror',
					'data-target'		=> '.content-block',
					'placeholder'		=> '<!-- Please paste your svg code here. Example: <svg>...</svg> -->',
					'default'			=> '',
					'button-title'		=> 'SVG Code',
					'class'				=> 'semplice-button codemirror white-button admin-click-handler',
					'style-class'		=> 'ov-logo-img cb-hidden',
					'data-handler'		=> 'codemirror',
				),
				'logo_padding_left' => array(
					'title'				=> 'Logo Padding Left',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'data-handler'		=> 'navigations',
					'class'				=> 'admin-listen-handler',
					'data-target'		=> '.logo',
					'data-css-attribute'=> 'padding-left',
					'default'			=> 40,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'data-range-slider' => 'navigations',
					'data-cb-option'	=> true,
					'style-class'		=> 'is-cb-option',
				),
				'logo_padding_right' => array(
					'title'				=> 'Logo Padding Right',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'data-handler'		=> 'navigations',
					'class'				=> 'admin-listen-handler',
					'data-target'		=> '.logo',
					'data-css-attribute'=> 'padding-right',
					'default'			=> 40,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'data-range-slider' => 'navigations',
					'data-cb-option'	=> true,
					'style-class'		=> 'is-cb-option',
				),
				'logo_margin_bottom' => array(
					'title'				=> 'Logo Bottom Margin',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'data-handler'		=> 'navigations',
					'class'				=> 'admin-listen-handler',
					'data-target'		=> '.logo',
					'data-css-attribute'=> 'margin-bottom',
					'default'			=> 20,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'data-range-slider' => 'navigations',
					'data-cb-option'	=> true,
					'style-class'		=> 'is-cb-option',
				),
				'logo_alignment' => array(
					'title'				=> 'Alignment',
					'size'				=> 'span4',
					'data-input-type'	=> 'select-box',
					'data-target'		=> '.logo',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'data-css-attribute'=> 'align-items',
					'data-target'		=> '.logo',
					'help'				=> 'This setting has no effect on some navigations.',
					'style-class'	 	=> 'logo-alignment cb-hidden',
					'select-box-values' => array(
						'center'	 => 'Middle',
						'flex-start' => 'Top',
					),
				),
			),
			'navigation_bar' => array(
				'title' => 'Navigation Bar',
				'break' => '2,2,2,1,1',
				'hide-title' => false,
				'navbar_type' => array(
					'data-input-type' 			=> 'switch',
					'help'						=> 'For certain navigations (for example, centered navs) this setting is irrelevant.',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Width',
					'size'		 				=> 'span2',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'navigations',
					'data-visibility-switch' 	=> true,
					'data-visibility-values' 	=> 'container,container-fluid',
					'data-visibility-prefix'	=> 'ov-navwidth',
					'default' 	 				=> 'container',
					'style-class'				=> 'navbar-type cb-hidden',
					'switch-values' => array(
						'container'  		=> 'Grid',
						'container-fluid'	=> 'Fluid',
					),
				),
				'navbar_mode' => array(
					'data-input-type' 			=> 'switch',
					'help'						=> 'Select \'Sticky\' if you want your navbar to stick to the top of the page on scroll.',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Mode',
					'size'		 				=> 'span2',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'navigations',
					'data-target'				=> 'none',
					'default' 	 				=> 'sticky',
					'style-class'				=> 'navbar-mode cb-hidden',
					'switch-values' => array(
						'sticky'  	=> 'Sticky',
						'normal'	=> 'Normal',
					),
				),
				'navbar_padding' => array(
					'title'				=> 'Padding Hor',
					'help'				=> 'If you have a centered menu and logo this setting is still viable for the mobile hamburger fallback.',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'data-handler'		=> 'navigations',
					'class'				=> 'admin-listen-handler',
					'data-target'		=> '.navbar-left',
					'data-css-attribute'=> 'left',
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'style-class'		=> 'ov-navwidth-container-fluid is-cb-option',
					'data-range-slider' => 'navigations',
					'data-cb-option'	=> true,
				),
				'navbar_padding_vertical' => array(
					'title'				=> 'Padding Ver',
					'help'				=> 'If you have a top-aligned logo and menu, you can adjust spacing with this option.<br /><br />Note: If you\'re using this setting, we recommend setting a transparent navbar background and a navbar height of 0.',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'data-handler'		=> 'navigations',
					'class'				=> 'admin-listen-handler',
					'data-target'		=> '.semplice-navbar',
					'data-css-attribute'=> 'padding',
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'data-range-slider' => 'navigations',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'navbar_height' => array(
					'title'				=> 'Height',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'data-handler'		=> 'navigations',
					'class'				=> 'admin-listen-handler',
					'data-target'		=> '.semplice-navbar',
					'data-css-attribute'=> 'height',
					'default'			=> 70,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'data-range-slider' => 'navigations',
					'style-class'		=> 'navbar-height is-cb-option',
					'data-cb-option'	=> true,
				),
				'navbar_bg_color' => array(
					'title'			=> 'Background',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'data-target'	=> '.semplice-navbar',
					'data-css-attribute' => 'background-color',
					'default'		=> '#f5f5f5',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'data-picker'		=> 'navigations',
					'style-class'		=> 'navbar-bg cb-hidden',
				),
				'navbar_bg_opacity' => array(
					'title'				=> 'BG Opacity',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'data-handler'		=> 'navigations',
					'class'				=> 'admin-listen-handler',
					'min'				=> 0,
					'max'				=> 100,
					'default'			=> 100,
					'data-divider'		=> 100,
					'data-range-slider' => 'navigations',
					'style-class'		=> 'navbar-bg-opacity cb-hidden',
				),
				'navbar_cover_transparent' => array(
					'title'				=> 'Transparent while in Cover',
					'help'				=> 'Enabled, your navbar background will be transparent while above the cover image or video. After the cover, your defined background-color will fade in on scroll.',
					'data-input-type' 	=> 'switch',
					'switch-type'		=> 'twoway',
					'size'				=> 'span4',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'default'			=> 'disabled',
					'data-target'		=> 'none',
					'style-class'		=> 'navbar-cover-transparent cb-hidden',
					'switch-values' => array(
						'disabled'		=> 'Disabled',
						'enabled'		=> 'Enabled'
					),
				),
				'navbar_bg_visibility_overlay' => array(
					'title'				=> 'Background Visibility in Overlay',
					'help'				=> 'Select \'hidden\' if you want to hide the navbar background while the overlay is open.',
					'data-input-type' 	=> 'switch',
					'switch-type'		=> 'twoway',
					'size'				=> 'span4',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'default'			=> 'visible',
					'data-target'		=> 'none',
					'style-class'		=> 'cb-hidden',
					'switch-values' => array(
						'visible'		=> 'Visible',
						'hidden'		=> 'Hidden'
					),
				),
				/*
				'preset' => array(
					'data-input-type' 	=> 'button',
					'title'		 		=> 'Navigation Preset',
					'button-title'		=> 'Change Preset',
					'size'		 		=> 'span4',
					'class'				=> 'white-button semplice-button admin-listen-handler',
					'data-handler'		=> 'navigations', 
				),
				*/
			),
		),

		'menu' => array(
			'edit_menu' => array(
				'title' => 'Edit Menu',
				'break' => '1',
				'hide-title' => false,
				'style-class' => 'cb-hidden',
				'categories' => array(
					'data-input-type' 	=> 'button',
					'hide-title'		=> true,
					'title'		 		=> 'Edit Menu Items',
					'button-title'		=> 'Edit Menu Items',
					'size'		 		=> 'span4',
					'class'				=> 'semplice-button admin-click-handler',
					'data-handler'		=> 'editMenu',
				),
			),
			'menu_options' => array(
				'title' => 'Menu Options',
				'break' => '1,2,2,2,2,2,2,2,1',
				'hide-title' => false,
				'menu_type' => array(
					'help'						=> 'To customize your hamburger icon, go to the \'Overlay/Mobile\' tab. ',
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Type',
					'size'		 				=> 'span4',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'navigations',
					'default' 	 				=> 'text',
					'data-target'				=> 'none',
					'style-class'				=> 'cb-hidden',
					'switch-values' => array(
							'text'  		=> 'Text',
						'hamburger'	 	=> 'Hamburger',
					),
				),
				'menu_font_family' => array(
					'title'				=> 'Font Family',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-fonts',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'data-target'		=> 'nav.standard',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => $fonts,
				),
				'menu_fontsize' => array(
					'title'				=> 'Fontsize',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 15,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'data-target'		=> '.semplice-navbar li a span',
					'data-css-attribute'=> 'font-size',
					'data-range-slider' => 'navigations',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'menu_color' => array(
					'title'			=> 'Color',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'default'		=> 'transparent',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'data-target'		=> '.semplice-navbar li a span',
					'data-css-attribute'=> 'color',
					'data-picker'		=> 'navigations',
					'style-class'		=> 'cb-hidden',
				),
				'menu_padding' => array(
					'title'				=> 'Items Padding',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'data-target'		=> '.semplice-navbar li a',
					'data-css-attribute'=> 'padding-right',
					'default'			=> 30,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'data-range-slider' => 'navigations',
					'style-class'		=> 'menu-padding is-cb-option',
					'data-cb-option'	=> true,
				),
				'menu_text_transform' => array(
					'title'				=> 'Text Transform',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'default'			=> 'none',
					'style-class'		=> 'ov-menu-text cb-hidden',
					'data-target'		=> '.semplice-navbar li a span',
					'data-css-attribute'=> 'text-transform',
					'select-box-values' => array(
						'none'			=> 'None',
						'uppercase'		=> 'Uppercase',
					),
				),
				'menu_letter_spacing' => array(
					'title'				=> 'Letter Spacing',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 9999,
					'data-divider'		=> 10,
					'data-has-unit'		=> true,
					'data-negative' 	=> true,
					'help'				=> 'Letter spacing will be adjusted in 0.1px increments.<br /><br /><b>Example:</b> 10 = 1px',
					'data-target'		=> '.semplice-navbar li a span',
					'data-css-attribute'=> 'letter-spacing',
					'data-range-slider' => 'navigations',
					'style-class'		=> 'cb-hidden',
				),
				'menu_border_color' => array(
					'title'			=> 'Underline Color',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'default'		=> '#000000',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'data-target'		=> 'li a span',
					'data-css-attribute'=> 'border-bottom-color',
					'data-picker'		=> 'navigations',
					'style-class'		=> 'cb-hidden',
				),
				'menu_border' => array(
					'title'				=> 'Underline',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 1000,
					'data-has-unit'		=> true,
					'data-target'		=> '.semplice-navbar li a span',
					'data-css-attribute'=> 'border-bottom-width',
					'data-range-slider' => 'navigations',
					'style-class'		=> 'cb-hidden',
				),
				'menu_border_padding' => array(
					'title'				=> 'Underline Padding',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 1000,
					'data-has-unit'		=> true,
					'data-target'		=> '.semplice-navbar li a span',
					'data-css-attribute'=> 'padding-bottom',
					'data-range-slider' => 'navigations',
					'style-class'		=> 'cb-hidden',
				),
				'menu_alignment' => array(
					'title'				=> 'Alignment',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'data-target'		=> 'nav.standard ul',
					'data-css-attribute'=> 'align-items',
					'help'				=> 'Please note: For navigations with a fixed alignment, this setting will have no effect.',
					'style-class'		=> 'menu-alignment cb-hidden',
					'select-box-values' => array(
						'center'	 => 'Middle',
						'flex-start' => 'Top',
					),
				),
				'menu_mobile_fallback' => array(
					'help'						=> 'Select \'Disabled\' if you want to disable the mobile fallback (hamburger) and show your menu instead',
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Mobile Hamburger Fallback',
					'size'		 				=> 'span4',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'navigations',
					'default' 	 				=> 'enabled',
					'data-target'				=> 'none',
					'style-class'				=> 'menu-mobile-fallback cb-hidden',
					'switch-values' => array(
						'enabled'	 	=> 'Enabled',
						'disabled'  	=> 'Disabled',
					),
				),
			),
			'mouseover_options' => array(
				'title' => 'Mouseover Options',
				'break' => '2',
				'hide-title' => false,
				'style-class'	=> 'ov-menu-text cb-hidden',
				'help'			=> 'The mouseover color will be also the color of your active link.',
				'menu_mouseover_color' => array(
					'title'			=> 'TextColor',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'default'		=> 'transparent',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'style-class'	=> 'ov-menu-text',
					'data-target'	=> 'mouseover',
					'data-picker'		=> 'navigations',
				),
				'menu_border_mouseover_color' => array(
					'title'			=> 'Border Color',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'default'		=> 'transparent',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'style-class'	=> 'ov-menu-text',
					'data-target'	=> 'mouseover',
					'data-picker'		=> 'navigations',
				),
			),
		),
		'overlay' => array(
			'hamburger_options' => array(
				'title' => 'Hamburger',
				'break' => '1,2,2,1,2,2',
				'hide-title' => false,
				'hamburger_mode' => array(
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Type',
					'size'		 				=> 'span4',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'navigations',
					'default' 	 				=> 'default',
					'data-target'				=> 'none',
					'data-visibility-switch' 	=> true,
					'data-visibility-values' 	=> 'default,custom',
					'data-visibility-prefix'	=> 'ov-hamburger',
					'style-class'				=> 'cb-hidden',
					'switch-values' => array(
						'default'	 => 'Default',
						'custom'  	=> 'Custom',
					),
				),
				'hamburger_color' => array(
					'title'			=> 'Color',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'default'		=> 'transparent',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'data-target'		=> '.open-menu span',
					'data-css-attribute'=> 'background-color',
					'data-picker'		=> 'navigations',
					'style-class'		=> 'ov-hamburger-default cb-hidden',
				),
				'hamburger_width' => array(
					'title'				=> 'Width',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 24,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'data-range-slider' => 'navigations',
					'data-cb-option'	=> true,
					'style-class'		=> 'ov-hamburger-default is-cb-option',
				),
				'hamburger_thickness' => array(
					'title'				=> 'Thickness',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 2,
					'min'				=> 0,
					'max'				=> 9999,
					'data-target'		=> '.open-menu span',
					'data-css-attribute'=> 'height',
					'data-range-slider' => 'navigations',
					'data-cb-option'	=> true,
					'style-class'		=> 'ov-hamburger-default is-cb-option',
				),
				'hamburger_padding' => array(
					'title'				=> 'Padding',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 6,
					'min'				=> 0,
					'max'				=> 9999,
					'data-range-slider' => 'navigations',
					'data-cb-option'	=> true,
					'style-class'		=> 'ov-hamburger-default is-cb-option',
				),
				'hamburger_alignment' => array(
					'title'				=> 'Alignment',
					'size'				=> 'span4',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'data-css-attribute'=> 'align-items',
					'data-target'		=> '.hamburger',
					'help'				=> 'This setting is has no effect on some navigations.',
					'style-class'		=> 'hamburger-alignment ov-hamburger-default cb-hidden',
					'select-box-values' => array(
						'center'	 => 'Middle',
						'flex-start' => 'Top',
					),
				),
				'hamburger_custom_width' => array(
					'title'				=> 'Width',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 24,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'data-css-attribute'=> 'width',
					'data-target'		=> '.hamburger img',
					'style-class'		=> 'ov-hamburger-custom is-cb-option',
					'data-range-slider' => 'navigations',
					'data-cb-option'	=> true,
				),
				'hamburger_custom_mouseover' => array(
					'title'				=> 'Mouseover',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'data-target'		=> '.hamburger',
					'style-class'		=> 'hamburger-alignment',
					'style-class'		=> 'ov-hamburger-custom cb-hidden',
					'select-box-values' => array(
						'scale'	 => 'Scale',
						'none'	 => 'None',
					),
				),
				'hamburger_custom' => array(
					'title'				=> 'Hamburger Icon',
					'help'				=> 'Upload your custom hamburger icon here. For best results, use an SVG file.',
					'size'				=> 'span2',
					'data-input-type'	=> 'admin-image-upload',
					'data-target'		=> '.content-block',
					'default'			=> '',
					'class'				=> 'admin-listen-handler',
					'style-class'   	=> 'ov-hamburger-custom ce-upload-small hide-unsplash cb-hidden',
					'data-handler'		=> 'navigations',
					'data-upload'		=> 'customHamburger',
				),
				'hamburger_custom_close' => array(
					'title'				=> 'Close Menu Icon',
					'help'				=> 'This icon will appear when you click to close your hamburger menu. For best results, both icons should have the same dimensions.<br /><br />Please note there is no preview for the close icon.',
					'size'				=> 'span2',
					'data-input-type'	=> 'admin-image-upload',
					'data-target'		=> '.content-block',
					'default'			=> '',
					'class'				=> 'admin-listen-handler',
					'style-class'   	=> 'ov-hamburger-custom ce-upload-small hide-unsplash cb-hidden',
					'data-handler'		=> 'navigations',
					'data-upload'		=> 'customHamburger',
				),
			),
			'overlay_options' => array(
				'title' => 'Overlay Menu',
				'break' => '1,2,2,2,2,2,2,2,2,2',
				'hide-title' => false,
				'overlay_type' => array(
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Width',
					'size'		 				=> 'span4',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'navigations',
					'data-visibility-switch' 	=> true,
					'data-visibility-values' 	=> 'container,container-fluid',
					'data-visibility-prefix'	=> 'ov-overlaywidth',
					'default' 	 				=> 'container',
					'data-target'				=> 'none',
					'style-class'				=> 'cb-hidden',
					'switch-values' => array(
						'container'  		=> 'Grid',
						'container-fluid'	=> 'Fluid',
					),
				),
				'overlay_bg_color' => array(
					'title'			=> 'Background',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'default'		=> 'transparent',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'data-picker'	=> 'navigations',
					'style-class'	=> 'cb-hidden',
				),
				'overlay_bg_opacity' => array(
					'title'				=> 'BG Opacity',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'data-handler'		=> 'navigations',
					'class'				=> 'admin-listen-handler',
					'min'				=> 0,
					'max'				=> 100,
					'default'			=> 100,
					'data-divider'		=> 100,
					'data-range-slider' => 'navigations',
					'style-class'		=> 'cb-hidden',
				),
				'overlay_padding_left' => array(
					'title'				=> 'Padding Left',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'data-handler'		=> 'navigations',
					'class'				=> 'admin-listen-handler',
					'data-target'		=> '#overlay-menu li a span',
					'data-css-attribute'=> 'left',
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'style-class'		=> 'ov-overlaywidth-container-fluid cb-hidden',
					'data-range-slider' => 'navigations',
				),
				'overlay_padding_right' => array(
					'title'				=> 'Padding Right',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'data-handler'		=> 'navigations',
					'class'				=> 'admin-listen-handler',
					'data-target'		=> '#overlay-menu li a span',
					'data-css-attribute'=> 'right',
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'style-class'		=> 'ov-overlaywidth-container-fluid cb-hidden',
					'data-range-slider' => 'navigations',
				),
				'overlay_padding_top' => array(
					'title'				=> 'Padding Top',
					'help'				=> 'Top padding will only be applied if the vertical alignment for your menu is set to \'Top\'.',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'data-handler'		=> 'navigations',
					'class'				=> 'admin-listen-handler',
					'data-target'		=> '#overlay-menu nav',
					'data-css-attribute'=> 'padding-top',
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'style-class'		=> 'cb-hidden',
					'data-range-slider' => 'navigations',
				),
				'overlay_alignment_ver' => array(
					'title'				=> 'Alignment Ver',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'data-target'		=> '.overlay-menu-inner',
					'data-default'		=> 'middle',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => array(
						'align-middle'	=> 'Middle',
						'align-top'		=> 'Top',
					),
				),
				'overlay_alignment_hor' => array(
					'title'				=> 'Alignment Hor',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'data-target'		=> '#overlay-menu nav',
					'data-css-attribute'=> 'text-align',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => array(
						'center'	 => 'Center',
						'left' => 'Left',
						'right'	 => 'Right'
					),
				),
				'overlay_font_family' => array(
					'title'				=> 'Font Family',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-fonts',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'data-target'		=> '.overlay-nav',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => $fonts,
				),
				'overlay_fontsize' => array(
					'title'				=> 'Fontsize',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 32,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'data-target'		=> '#overlay-menu li a span',
					'data-css-attribute'=> 'font-size',
					'data-range-slider' => 'navigations',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'overlay_color' => array(
					'title'			=> 'Link Color',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'default'		=> 'transparent',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'data-target'		=> '#overlay-menu li a span',
					'data-css-attribute'=> 'color',
					'data-picker'		=> 'navigations',
					'style-class'		=> 'cb-hidden',
				),
				'overlay_padding' => array(
					'title'				=> 'Items Padding',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 20,
					'min'				=> 0,
					'max'				=> 9999,
					'data-has-unit'		=> true,
					'data-target'		=> '#overlay-menu li a',
					'data-css-attribute'=> 'padding-bottom',
					'data-range-slider' => 'navigations',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'overlay_text_transform' => array(
					'title'				=> 'Text Transform',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'navigations',
					'default'			=> 'none',
					'data-target'		=> '#overlay-menu li a span',
					'data-css-attribute'=> 'text-transform',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => array(
						'none'			=> 'None',
						'uppercase'		=> 'Uppercase',
					),
				),
				'overlay_letter_spacing' => array(
					'title'				=> 'Letter Spacing',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 9999,
					'data-divider'		=> 10,
					'data-has-unit'		=> true,
					'data-negative' 	=> true,
					'help'				=> 'Letter spacing will be adjusted in 0.1px increments.<br /><br /><b>Example:</b> 10 = 1px',
					'data-target'		=> '#overlay-menu li a span',
					'data-css-attribute'=> 'letter-spacing',
					'data-range-slider' => 'navigations',
					'style-class'		=> 'cb-hidden',
				),
				'overlay_border_color' => array(
					'title'			=> 'Underline Color',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'default'		=> '#000000',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'data-target'		=> '#overlay-menu li a span',
					'data-css-attribute'=> 'border-bottom-color',
					'data-picker'		=> 'navigations',
					'style-class'		=> 'cb-hidden',
				),
				'overlay_border' => array(
					'title'				=> 'Underline',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 1000,
					'data-has-unit'		=> true,
					'data-target'		=> '#overlay-menu li a span',
					'data-css-attribute'=> 'border-bottom-width',
					'data-range-slider' => 'navigations',
					'style-class'		=> 'cb-hidden',
				),
				'overlay_border_padding' => array(
					'title'				=> 'Underline Padding',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'logo-font-size admin-listen-handler',
					'data-handler'		=> 'navigations',
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 1000,
					'data-has-unit'		=> true,
					'data-target'		=> '#overlay-menu li a span',
					'data-css-attribute'=> 'padding-bottom',
					'data-range-slider' => 'navigations',
					'style-class'		=> 'cb-hidden',
				),
			),
			'overlay_mouseover_options' => array(
				'title' => 'Mouseover Options',
				'break' => '2',
				'hide-title' => false,
				'help'			=> 'The color you choose here will also define the color of your active links.',
				'style-class' => 'cb-hidden',
				'overlay_mouseover_color' => array(
					'title'			=> 'TextColor',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'default'		=> 'transparent',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'data-target'	=> 'mouseover',
					'data-picker'	=> 'navigations',
				),
				'overlay_border_mouseover_color' => array(
					'title'			=> 'Border Color',
					'size'			=> 'span2',
					'data-input-type'	=> 'color',
					'default'		=> 'transparent',
					'class'			=> 'color-picker admin-listen-handler',
					'data-handler'  => 'colorPicker',
					'data-target'	=> 'mouseover',
					'data-picker'	=> 'navigations',
				),
			),
		),
	),
);