<?php

// -----------------------------------------
// semplice
// admin/atts/customize/projectnav.php
// -----------------------------------------

$projectnav = array(
	'tabs' => array(
		'nextprev' => array(
			'np-options' => array(
				'title' => 'Options',
				'hide-title'	=> true,
				'break'	=> '2,2,3',
				'np_visibility' => array(
					'title'				=> 'Visibility',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'default'			=> 'visible',
					'help'				=> 'This will toggle the visibility of the next / prev container on your projects.',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => array(
						'visible'		=> 'Visible',
						'hidden'		=> 'Hidden',
					),
				),
				'np_next_only' => array(
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Show next only',
					'size'		 				=> 'span2',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'projectnav',
					'default' 	 				=> 'disabled',
					'style-class'		=> 'cb-hidden',
					'switch-values' => array(
						'disabled' => 'No',
						'enabled'  => 'Yes',
					),
				),
				'np_width' => array(
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Width',
					'size'		 				=> 'span2',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'projectnav',
					'default' 	 				=> 'grid',
					'style-class'		=> 'cb-hidden',
					'switch-values' => array(
						'grid'  				=> 'Grid',
						'fluid'	 				=> 'Fluid',
					),
				),
				'np_gutter' => array(
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Gutter',
					'size'		 				=> 'span2',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'projectnav',
					'default' 	 				=> 'yes',
					'style-class'		=> 'cb-hidden',
					'switch-values' => array(
						'yes'  => 'Keep',
						'no'   => 'Remove',
					),
				),
				'np_height' => array(
					'title'			=> 'Height',
					'size'			=> 'span1',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 180,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.semplice-next-prev .np-inner',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'data-css-attribute' => 'height',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'np_background' => array(
					'title'				=> 'BG Color',
					'size'				=> 'span1',
					'data-input-type'	=> 'color',
					'data-target'		=> '.semplice-next-prev',
					'default'			=> '#ffffff',
					'class'				=> 'color-picker admin-listen-handler',
					'data-handler' 		=> 'colorPicker',
					'data-picker'		=> 'projectnav',
					'style-class'		=> 'cb-hidden',
				),
			),
			'np-spacings' => array(
				'title' => 'Spacing',
				'break'	=> '2,2',
				'style-class' => 'ep-collapsed',
				'np_padding_outer_top' => array(
					'title'			=> 'Outer Top',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 0,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.semplice-next-prev',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'np_padding_outer_bottom' => array(
					'title'			=> 'Outer Bottom',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 0,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.semplice-next-prev',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'np_padding_ver' => array(
					'title'			=> 'Text Vertical',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 0,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.np-text',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'help'				=> 'This setting only takes effect if both the option \'Text Position\' is set to \'Above\' or \'Below\' and thumbnails are visible.',
					'data-cb-option'	=> true,
				),
				'np_padding_hor' => array(
					'title'			=> 'Text Horizontal',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 0,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.np-text',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'help'			=> 'Has no effect if text is centered.',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
			),
			'np-image-options' => array(
				'title' => 'Thumbnail Options',
				'break'	=> '2',
				'style-class' => 'ep-collapsed cb-hidden',
				'help'	=> 'You can define your \'Next / Prev\' thumbnails in the page settings of your project. Note that only thumbnails from pubslihed projects will show up.',
				'np_image_visibility' => array(
					'title'				=> 'Visibility',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'default'			=> 'hidden',
					'select-box-values' => array(
						'hidden'		=> 'Hidden',
						'visible'		=> 'Visible',
					),
				),
				'np_image_scale' => array(
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Scale',
					'size'		 				=> 'span2',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'projectnav',
					'default' 	 				=> 'cover',
					'switch-values' => array(
						'cover'  => 'Cover',
						'contain'   => 'Contain',
					),
				),
			),
			'np-text-options' => array(
				'title' => 'Text Options',
				'break'	=> '2,2,1',
				'style-class' => 'ep-collapsed cb-hidden',
				'np_text_visibility' => array(
					'title'				=> 'Visibility',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'default'			=> 'visible',
					'select-box-values' => array(
						'visible'		=> 'Visible',
						'hidden'		=> 'Hidden',
					),
				),
				'np_label' => array(
					'title'				=> 'Labels',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'default'			=> 'nextprev_above_title',
					'select-box-values' => array(
						'arrows'				=> 'Arrows',
						'nextprev'				=> 'Next/Previous',
						'title'					=> 'Project Title',
						'arrows_nextprev'		=> 'Arrows with Next/Previous',
						'arrows_title'			=> 'Arrows with project title',
						'nextprev_above_title'	=> 'Next/Previous above project title',
						'type_above_title'		=> 'Project Type above project title',
					)
				),
				'np_justify' => array(
					'title'				=> 'Text Justify',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'default'			=> 'edge',
					'select-box-values' => array(
						'edge'		=> 'Edge',
						'center'	=> 'Center',
						'inner'		=> 'Inner'
					),
				),
				'np_text_position' => array(
					'title'				=> 'Text Position',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'default'			=> 'overlay',
					'help'				=> 'This setting only takes effect if the visibility for both text and thumbnails is set to \'Visible\'.',
					'data-visibility-switch' 	=> true,
					'data-visibility-values' 	=> 'overlay,above,below',
					'data-visibility-prefix'	=> 'ov-np-position',
					'select-box-values' => array(
						'overlay'	=> 'Overlay',
						'above'		=> 'Above',
						'below'		=> 'Below'
					),
				),
				'np_alignment' => array(
					'title'				=> 'Text Align',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'default'			=> 'edge',
					'style-class'		=> 'ov-np-position-overlay',
					'select-box-values' => array(
						'middle'	=> 'Middle',
						'top'		=> 'Top',
						'bottom'	=> 'Bottom'
					),
				),
			),
			'np-typography' => array(
				'title' => 'Label Formatting',
				'break'	=> '3,2',
				'style-class' => 'ep-collapsed',
				'np_color' => array(
					'title'				=> 'Color',
					'size'				=> 'span1',
					'data-input-type'	=> 'color',
					'data-target'		=> '.semplice-next-prev .np-link .np-prefix, .semplice-next-prev .np-link .np-label',
					'default'			=> '#000000',
					'class'				=> 'color-picker admin-listen-handler',
					'data-handler' 		=> 'colorPicker',
					'data-picker'		=> 'projectnav',
					'style-class'		=> 'cb-hidden',
				),
				'np_fontsize' => array(
					'title'			=> 'Font Size',
					'size'			=> 'span1',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 28,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'		=> '.semplice-next-prev .np-link .np-prefix, .semplice-next-prev .np-link .np-label',
					'data-css-attribute' => 'font-size',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'np_font' => array(
					'data-input-type' => 'select-fonts',
					'title'		 		=> 'Font Family',
					'size'		 		=> 'span2',
					'default' 	 		=> 'none',
					'data-target'		=> '.semplice-next-prev .np-link .np-prefix, .semplice-next-prev .np-link .np-label',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'select-box-values' => $fonts,
					'style-class'		=> 'cb-hidden',
				),
				'np_text_transform' => array(
					'title'				=> 'Text Transform',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'projectnav',
					'data-css-attribute'=> 'text-transform',
					'data-target'		=> '.semplice-next-prev .np-link .np-prefix, .semplice-next-prev .np-link .np-label',
					'default'			=> 'none',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => array(
						'none'			=> 'None',
						'uppercase'		=> 'Uppercase',
					),
				),
				'np_letter_spacing' => array(
					'title'				=> 'Letter Spacing',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'projectnav',
					'data-css-attribute'=> 'letter-spacing',
					'data-target'		=> '.semplice-next-prev .np-link .np-prefix, .semplice-next-prev .np-link .np-label',
					'data-has-unit'		=> true,
					'default'			=> 0,
					'min'				=> 0,
					'max'				=> 9999,
					'data-negative' 	=> true,
					'data-divider'		=> 10,
					'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
					'data-range-slider' => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
			),
			'np-typography-sub' => array(
				'title' => 'Subtext Formatting',
				'break'	=> '3,2,1',
				'style-class' => 'ep-collapsed',
				'np_color_sub' => array(
					'title'				=> 'Color',
					'size'				=> 'span1',
					'data-input-type'	=> 'color',
					'data-target'		=> '.semplice-next-prev .np-link .np-label-above',
					'default'			=> '#aaaaaa',
					'class'				=> 'color-picker admin-listen-handler',
					'data-handler' 		=> 'colorPicker',
					'data-picker'		=> 'projectnav',
					'style-class'		=> 'cb-hidden',
				),
				'np_fontsize_sub' => array(
					'title'			=> 'Font Size',
					'size'			=> 'span1',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 14,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'		=> '.semplice-next-prev .np-link .np-label-above',
					'data-css-attribute' => 'font-size',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'np_font_sub' => array(
					'data-input-type' => 'select-fonts',
					'title'		 		=> 'Font Family',
					'size'		 		=> 'span2',
					'default' 	 		=> 'none',
					'data-target'		=> '.semplice-next-prev .np-link .np-label-above',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'select-box-values' => $fonts,
					'style-class'		=> 'cb-hidden',
				),
				'np_text_transform_sub' => array(
					'title'				=> 'Text Transform',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'projectnav',
					'data-css-attribute'=> 'text-transform',
					'data-target'		=> '.semplice-next-prev .np-link .np-label-above',
					'default'			=> 'uppercase',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => array(
						'uppercase'		=> 'Uppercase',
						'none'			=> 'None',
					),
				),
				'np_letter_spacing_sub' => array(
					'title'				=> 'Letter Spacing',
					'size'				=> 'span2',
					'offset'			=> false,
					'data-input-type' 	=> 'range-slider',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'projectnav',
					'data-css-attribute'=> 'letter-spacing',
					'data-target'		=> '.semplice-next-prev .np-link .np-label-above',
					'data-has-unit'		=> true,
					'default'			=> 10,
					'min'				=> 0,
					'max'				=> 9999,
					'data-negative' 	=> true,
					'data-divider'		=> 10,
					'help'				=> 'This value increments the letter spacing in 0.1px steps. <br /><br /><b>Example:</b> 10 = 1px',
					'data-range-slider' => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'np_spacing_sub' => array(
					'title'			=> 'Spacing',
					'size'			=> 'span1',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 2,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'		=> '.semplice-next-prev .np-link .np-text-above',
					'data-css-attribute' => 'padding-bottom',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
			),
			'np-seperator' => array(
				'title' => 'Seperator',
				'break'	=> '2,2',
				'style-class' => 'ep-collapsed',
				'np_sep_visibility' => array(
					'title'				=> 'Visibility',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'default'			=> 'hidden',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => array(
						'hidden'		=> 'Hidden',
						'visible'		=> 'Visible',
					),
				),
				'np_sep_background' => array(
					'title'				=> 'Color',
					'size'				=> 'span2',
					'data-input-type'	=> 'color',
					'data-target'		=> '.nextprev-seperator',
					'default'			=> '#000000',
					'class'				=> 'color-picker admin-listen-handler',
					'data-handler' 		=> 'colorPicker',
					'data-picker'		=> 'projectnav',
					'style-class'		=> 'cb-hidden',
				),
				'np_sep_width' => array(
					'title'			=> 'Width',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 1,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.nextprev-seperator',
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'np_sep_spacing' => array(
					'title'			=> 'Vertical Spacing',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 30,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.nextprev-seperator',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
			),
			'np-mouseover' => array(
				'title' => 'Mouseover',
				'break'	=> '3,2,2',
				'style-class' => 'ep-collapsed cb-hidden',
				'help'	=> 'Please note that there is no preview for these mouseover effects.',
				'np_mouseover_background' => array(
					'title'				=> 'BG',
					'size'				=> 'span1',
					'data-input-type'	=> 'color',
					'data-target'		=> '.semplice-next-prev',
					'default'			=> '#ffffff',
					'class'				=> 'color-picker admin-listen-handler',
					'data-handler' 		=> 'colorPicker',
					'data-picker'		=> 'projectnav',
				),
				'np_mouseover_color' => array(
					'title'				=> 'Label',
					'size'				=> 'span1',
					'data-input-type'	=> 'color',
					'data-target'		=> '.semplice-next-prev .np-link',
					'default'			=> '#000000',
					'class'				=> 'color-picker admin-listen-handler',
					'data-handler' 		=> 'colorPicker',
					'data-picker'		=> 'projectnav',
				),
				'np_mouseover_color_sub' => array(
					'title'				=> 'Subtext',
					'size'				=> 'span1',
					'data-input-type'	=> 'color',
					'data-target'		=> '.semplice-next-prev .np-link',
					'default'			=> '#000000',
					'class'				=> 'color-picker admin-listen-handler',
					'data-handler' 		=> 'colorPicker',
					'data-picker'		=> 'projectnav',
				),
				'np_mouseover_effect' => array(
					'data-input-type' => 'select-box',
					'title'			=> 'Effects',
					'size'		 => 'span2',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'data-visibility-switch' 	=> true,
					'data-visibility-values' 	=> 'none,scale-opacity,dim-down',
					'data-visibility-prefix'	=> 'ov-np-mouseover',
					'default' 	 => 'none',
					'select-box-values' => array(
						'none'		 => 'None',
						'scale-opacity' => 'Scale hovered, dim down rest',
						'dim-down'		=> 'Dim down hovered',
					),
				),
				'np_mouseover_title_fade' => array(
					'data-input-type' => 'select-box',
					'title'		 => 'Title Fade In / out',
					'size'		 => 'span2',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'help'  => 'If you want to fade in the title on mouseover, set the \'Visibility\' under Text Options to \'Hidden\'. If you want to hide the title on hover, set the \'Visibility\' to something other than \'Hidden\'.',
					'default' 	 => 'none',
					'select-box-values' => array(
						'none'				=> 'None',
						'fadein' 		  	=> 'Fade in only',
						'fadein-top' 		=> 'Fade in + move from top',
						'fadein-edge' 		=> 'Fade in + move from edge',
						'fadein-bottom' 	=> 'Fade in + move from bottom',
						'fadein-inner' 		=> 'Fade in + move from inner',
						'fadeout' 		  	=> 'Fade out only',
						'fadeout-top' 		=> 'Fade out + move to top',
						'fadeout-edge' 		=> 'Fade out + move to edge',
						'fadeout-bottom' 	=> 'Fade out + move to bottom',
						'fadeout-inner' 	=> 'Fade out + move to inner',
					),
				),
				'np_mouseover_so_opacity' => array(
					'title'			=> 'Opacity',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' => 'range-slider',
					'default'		=> 40,
					'min'			=> 0,
					'max'			=> 100,
					'data-divider'	=> 100,
					'class'				=> 'admin-listen-handler',
					'data-range-slider' => 'projectnav',
					'data-handler'		=> 'projectnav',
					'data-target'		=> 'no-preview',
					'style-class'	=> 'ov-np-mouseover-scale-opacity'
				),
				'np_mouseover_so_scale' => array(
					'title'			=> 'Scale in %',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' => 'range-slider',
					'default'		=> 7,
					'min'			=> 0,
					'max'			=> 70,
					'class'				=> 'admin-listen-handler',
					'data-range-slider' => 'projectnav',
					'data-handler'		=> 'projectnav',
					'data-target'		=> 'no-preview',
					'style-class'	=> 'ov-np-mouseover-scale-opacity'
				),
				'np_mouseover_dimdown_opacity' => array(
					'title'			=> 'Opacity',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' => 'range-slider',
					'default'		=> 40,
					'min'			=> 0,
					'max'			=> 100,
					'data-divider'	=> 100,
					'class'				=> 'admin-listen-handler',
					'data-range-slider' => 'projectnav',
					'data-handler'		=> 'projectnav',
					'data-target'		=> 'no-preview',
					'style-class'	=> 'ov-np-mouseover-dim-down'
				),
			),
		),
		'projectpanel' => array(
			'pp-options' => array(
				'title' => 'Options',
				'hide-title'	=> true,
				'break'	=> '2,3,2,1',
				'visibility' => array(
					'title'				=> 'Panel Visibility',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'default'			=> 'visible',
					'help'				=> 'This will toggle the visibility of the project panel on your projects.',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => array(
						'visible'		=> 'Visible',
						'hidden'		=> 'Hidden',
					),
				),
				'hide_active_project' => array(
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Hide Active Project',
					'size'		 				=> 'span2',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'projectnav',
					'default' 	 				=> 'no',
					'style-class'		=> 'cb-hidden',
					'switch-values' => array(
						'no'  	=> 'No',
						'yes'	=> 'Yes',
					),
				),
				'images_per_row' => array(
					'title'				=> 'Thumbs per row',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'default'			=> '2',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
					'select-box-values' => array(
						'1'				=> '12',
						'2'				=> '6',
						'3'				=> '4',
						'4'				=> '3',
						'6'				=> '2',
						'12'			=> '1',
					),
				),
				'background' => array(
					'title'				=> 'BG Color',
					'size'				=> 'span1',
					'data-input-type'	=> 'color',
					'data-target'		=> '.pp-title a',
					'default'			=> '#f5f5f5',
					'class'				=> 'color-picker admin-listen-handler',
					'data-handler' 		=> 'colorPicker',
					'data-picker'		=> 'projectnav',
					'style-class'		=> 'cb-hidden',
				),
				'panel_padding' => array(
					'title'			=> 'Spacing',
					'size'			=> 'span1',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 45,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.project-panel',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'width' => array(
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Width',
					'size'		 				=> 'span2',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'projectnav',
					'default' 	 				=> 'container',
					'style-class'		=> 'cb-hidden',
					'switch-values' => array(
						'container'  	=> 'Grid',
						'container-fluid'	 	=> 'Fluid',
					),
				),
				'gutter' => array(
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Gutter',
					'size'		 				=> 'span2',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'projectnav',
					'default' 	 				=> 'yes',
					'style-class'		=> 'cb-hidden',
					'switch-values' => array(
						'yes'  => 'Keep',
						'no'   => 'Remove',
					),
				),
			),
			'panel_title_options' => array(
				'title'  	 => 'Panel Title Options',
				'break'		 => '1,2,2,2,2,2',
				'data-hide-mobile' => true,
				'style-class' => 'ep-collapsed',
				'panel_label'  => array(
					'title'				=> 'Label',
					'data-input-type'	=> 'input-text',
					'default'			=> 'Selected Works',
					'placeholder'		=> 'Selected Works',
					'size'				=> 'span4',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'style-class'		=> 'cb-hidden',
				),
				'title_visibility' => array(
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Visibility',
					'size'		 				=> 'span2',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'projectnav',
					'default' 	 				=> 'visible',
					'style-class'		=> 'cb-hidden',
					'switch-values' => array(
						'visible'  	=> 'Visible',
						'hidden'	=> 'Hidden',
					),
				),
				'panel_text_align' => array(
					'data-input-type' 			=> 'switch',
					'switch-type'				=> 'twoway',
					'title'		 				=> 'Alignment',
					'size'		 				=> 'span2',
					'class'						=> 'admin-listen-handler',
					'data-handler'				=> 'projectnav',
					'default' 	 				=> 'left',
					'data-css-attribute'		=> 'text-align',
					'data-target'				=> '.panel-label',
					'style-class'		=> 'cb-hidden',
					'switch-values' => array(
						'left'  	=> 'Left',
						'center'	=> 'Center',
					),
				),
				'panel_title_color' => array(
					'title'				=> 'Color',
					'size'				=> 'span2',
					'data-input-type'	=> 'color',
					'data-target'		=> '.panel-label',
					'default'			=> '#000000',
					'class'				=> 'color-picker admin-listen-handler',
					'data-handler' 		=> 'colorPicker',
					'data-picker'		=> 'projectnav',
					'style-class'		=> 'cb-hidden',
				),
				'panel_title_font' => array(
					'data-input-type' => 'select-fonts',
					'title'		 		=> 'Font Family',
					'size'		 		=> 'span2',
					'default' 	 		=> 'regular',
					'data-target'		=> '.panel-label span',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'select-box-values' => $fonts,
					'style-class'		=> 'cb-hidden',
				),
				'panel_title_fontsize' => array(
					'title'			=> 'Font Size',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 32,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.panel-label',
					'data-css-attribute' => 'font-size',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'panel_title_text_transform' => array(
					'title'				=> 'Text Transform',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'projectnav',
					'data-css-attribute'=> 'text-transform',
					'default'			=> 'none',
					'data-target'		=> '.panel-label',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => array(
						'none'			=> 'None',
						'uppercase'		=> 'Uppercase',
					),
				),
				'panel_padding_left' => array(
					'title'			=> 'Padding Left',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 0,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.panel-label',
					'data-css-attribute' => 'padding-left',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'panel_padding_bottom' => array(
					'title'			=> 'Padding Bottom',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 30,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.panel-label',
					'data-css-attribute' => 'padding-bottom',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
			),
			'title_options' => array(
				'title'  	 => 'Project Title Options',
				'break'		 => '1,2,2,2',
				'data-hide-mobile' => true,
				'style-class' => 'ep-collapsed',
				'meta_visibility' => array(
					'data-input-type' 	=> 'select-box',
					'title'		 		=> 'Title Visibility',
					'size'		 		=> 'span4',
					'class'				=> 'admin-listen-handler',
					'default' 	 		=> 'both',
					'data-handler'  	=> 'projectnav',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => array(
						'both' 			=> 'Show both title and project type',
						'title'			=> 'Show only title',
						'category'		=> 'Show only project type',
						'hidden'		=> 'Hide Both',
					),
				),
				'title_color' => array(
					'title'				=> 'Color',
					'size'				=> 'span2',
					'data-input-type'	=> 'color',
					'data-target'		=> '.pp-title a',
					'default'			=> '#000000',
					'class'				=> 'color-picker admin-listen-handler',
					'data-handler' 		=> 'colorPicker',
					'data-picker'		=> 'projectnav',
					'style-class'		=> 'cb-hidden',
				),
				'title_font' => array(
					'data-input-type' => 'select-fonts',
					'title'		 		=> 'Font Family',
					'size'		 		=> 'span2',
					'default' 	 		=> 'none',
					'data-target'		=> '.pp-title a',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'select-box-values' => $fonts,
					'style-class'		=> 'cb-hidden',
				),
				'title_fontsize' => array(
					'title'			=> 'Font Size',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 13,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.pp-title a',
					'data-css-attribute' => 'font-size',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'title_text_transform' => array(
					'title'				=> 'Text Transform',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'default'			=> 'none',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'projectnav',
					'data-css-attribute'=> 'text-transform',
					'data-target'		=> '.pp-title a',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => array(
						'none'			=> 'None',
						'uppercase'		=> 'Uppercase',
					),
				),
				'title_padding_top' => array(
					'title'			=> 'Padding Top',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 10,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.pp-title',
					'data-css-attribute' => 'padding-top',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'title_padding_bottom' => array(
					'title'			=> 'Padding Bottom',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 30,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.project-panel',
					'data-target'	=> '.pp-title',
					'data-css-attribute' => 'padding-bottom',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'help'				  => 'You will only see a preview if you have more than 1 row of thumbnails.',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
			),
			'type_options' => array(
				'title'  	 => 'Project Type Options',
				'break'		 => '2,2',
				'data-hide-mobile' => true,
				'style-class' => 'ep-collapsed',
				'category_color' => array(
					'title'				=> 'Color',
					'size'				=> 'span2',
					'data-input-type'	=> 'color',
					'data-target'		=> '.pp-title span',
					'default'			=> '#999999',
					'class'				=> 'color-picker admin-listen-handler',
					'data-handler' 		=> 'colorPicker',
					'data-picker'		=> 'projectnav',
					'style-class'		=> 'cb-hidden',
				),
				'category_font' => array(
					'data-input-type' => 'select-fonts',
					'title'		 		=> 'Font Family',
					'size'		 		=> 'span2',
					'default' 	 		=> 'none',
					'data-target'		=> '.pp-title span',
					'class'				=> 'admin-listen-handler',
					'data-handler'  	=> 'projectnav',
					'select-box-values' => $fonts,
					'style-class'		=> 'cb-hidden',
				),
				'category_fontsize' => array(
					'title'			=> 'Font Size',
					'size'			=> 'span2',
					'offset'		=> false,
					'data-input-type' 	=> 'range-slider',
					'default'		=> 13,
					'min'			=> 0,
					'max'			=> 999,
					'class'			=> 'admin-listen-handler',
					'data-target'	=> '.pp-title span',
					'data-css-attribute' => 'font-size',
					'data-has-unit'	=> true,
					'data-range-slider'   => 'projectnav',
					'data-handler'		  => 'projectnav',
					'style-class'		=> 'is-cb-option',
					'data-cb-option'	=> true,
				),
				'category_text_transform' => array(
					'title'				=> 'Text Transform',
					'size'				=> 'span2',
					'data-input-type'	=> 'select-box',
					'class'				=> 'admin-listen-handler',
					'data-handler'		=> 'projectnav',
					'data-css-attribute'=> 'text-transform',
					'data-target'		=> '.pp-title span',
					'default'			=> 'none',
					'style-class'		=> 'cb-hidden',
					'select-box-values' => array(
						'none'			=> 'None',
						'uppercase'		=> 'Uppercase',
					),
				),
			),
		),
	),
);