<?php

// -----------------------------------------
// semplice
// admin/atts/modules/beforeafter.php
// -----------------------------------------

$beforeafter = array(
	'images' => array(
		'title'  	 => 'Images',
		'break'		 => '2,2',
		'help'		 => 'For best results, make sure both images have the exact same dimensions. If your images do not have the same dimensions, the preview for the vertical direction will look distorted.<br /><br />For transparent images the placeholder background will still be visible in the editor.',
		'data-hide-mobile' => true,
		'before' => array(
			'title'			=> 'Before Image',
			'size'			=> 'span2',
			'data-input-type'	=> 'admin-image-upload',
			'default'		=> '',
			'class'			=> 'editor-listen',
			'style-class'   => 'ce-upload-small hide-unsplash',
			'data-upload'	=> 'beforeAfter',
		),
		'after' => array(
			'title'			=> 'After Image',
			'size'			=> 'span2',
			'data-input-type'	=> 'admin-image-upload',
			'default'		=> '',
			'class'			=> 'editor-listen',
			'style-class'   => 'ce-upload-small hide-unsplash',
			'data-upload'	=> 'beforeAfter',
		),
		'direction' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Direction',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'beforeAfter',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'horizontal,vertical',
			'data-visibility-prefix'	=> 'ov-ba-direction',
			'help'				=> 'The vertical preview will look distorted if your images are not sharing the same dimensions or if only one image is uploaded.',
			'default' 	 => 'horizontal',
			'switch-values' => array(
				'horizontal'	=> 'Hor',
				'vertical'	 	=> 'Ver',
			),
		),
		'start' => array(
			'title'			=> 'Start Position (%)',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 50,
			'min'			=> 0,
			'max'			=> 100,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'save',
			'help'			=> 'There is no live preview for the start position.',
		),
	),
	'handlebar' => array(
		'title'  	 => 'Handlebar',
		'break'		 => '3',
		'style-class'=> 'ep-collapsed',
		'data-hide-mobile' => true,
		'width' => array(
			'title'			=> 'Width',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 3,
			'min'			=> 0,
			'max'			=> 100,
			'data-style-option' => true,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'default',
			'data-target'	=> '.ba-bar',
			'style-class'	=> 'ov-ba-direction-horizontal',
		),
		'height' => array(
			'title'			=> 'Height',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 3,
			'min'			=> 0,
			'max'			=> 100,
			'data-style-option' => true,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'default',
			'data-target'	=> '.ba-bar',
			'style-class'	=> 'ov-ba-direction-vertical',
		),
		'background-color' => array(
			'title'			=> 'Color',
			'data-style-option' => true,
			'size'			=> 'span2',
			'data-input-type'	=> 'color',
			'data-target'	=> '.ba-bar',
			'default'		=> '#ffffff',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
		),
	),
	'arrows' => array(
		'title'  	 => 'Arrows',
		'break'		 => '4',
		'style-class'=> 'ep-collapsed',
		'data-hide-mobile' => true,
		'arrow_width' => array(
			'title'			=> 'Width',
			'size'			=> 'span1',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 16,
			'min'			=> 0,
			'max'			=> 100,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'baArrowWidth',
			'data-range-slider' => 'baArrowWidth',
			'data-has-unit'=> true,
			'data-target'	=> '.ba-arrow, .ba-arrow svg',
		),
		'stroke-width' => array(
			'title'			=> 'Stroke',
			'size'			=> 'span1',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 3,
			'min'			=> 0,
			'max'			=> 7,
			'data-style-option' => true,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'default',
			'data-target'	=> '.ba-arrow svg path',
		),
		'stroke' => array(
			'title'			=> 'Color',
			'data-style-option' => true,
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'data-target'	=> '.ba-arrow svg path',
			'default'		=> '#ffffff',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
		),
		'arrow_spacing' => array(
			'title'			=> 'Spacing',
			'size'			=> 'span1',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 15,
			'min'			=> 0,
			'max'			=> 100,
			'data-style-option' => true,
			'class'      	=> 'editor-listen',
			'data-handler' 	=> 'default',
			'data-target'	=> '.ba-arrow',
		),
	),
);

?>