<?php

// -----------------------------------------
// semplice
// admin/atts/modules/gallerygrid.php
// -----------------------------------------

$gallerygrid = array(
	'images-upload' => array(
		'title'  	 => 'Images',
		'break'		 => '1',
		'data-hide-mobile' => true,
		'images' => array(
			'title'				=> 'Images',
			'data-style-option' => true,
			'hide-title' 		=> true,
			'size'				=> 'span4',
			'data-input-type'	=> 'gallery-upload',
			'default'			=> '',
			'data-is-content' 	=> true,
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'style-class'		=> 'ce-dropzone ce-dropzone-no-unsplash gallery-upload',
		),
	),
	'refresh-grid' => array(
		'title'  	 => 'Refresh',
		'hide-title' => true,
		'break'		 => '1',
		'masonry' => array(
			'data-input-type' 	=> 'button',
			'title'		 		=> 'Preview',
			'button-title'		=> 'Refresh Grid',
			'hide-title'		=> true,
			'help'				=> 'If you are happy with your settings, just press the \'Refresh Grid\' button to generate a new preview with your updated settings.',
			'size'		 		=> 'span4',
			'class'				=> 'semplice-button regenerate-masonry',
			'responsive'		=> true,
		),
	),
	'options' => array(
		'title'  	 => 'Options',
		'hide-title' => true,
		'break'		 => '3,2',
		'data-hide-mobile' => true,
		'hor_gutter' => array(
			'title'			=> 'H-Gutter',
			'size'			=> 'span1',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 30,
			'min'			=> 0,
			'max'			=> 999,
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
		),
		'ver_gutter' => array(
			'title'			=> 'V-Gutter',
			'size'			=> 'span1',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 30,
			'min'			=> 0,
			'max'			=> 999,
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
		),
		'col' => array(
			'data-input-type' 	=> 'select-box',
			'title'		 		=> 'Images per Row',
			'size'		 		=> 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 		=> '4',
			'select-box-values' => array(
				'12' 			=> '1 Image',
				'6' 			=> '2 Images',
				'4' 			=> '3 Images',
				'3' 			=> '4 Images',
				'2' 			=> '6 Images',
				'1' 			=> '12 Images',
			),
		),
		'random' => array(
			'data-input-type' 	=> 'select-box',
			'title'		 		=> 'Random Grid',
			'size'		 		=> 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 		=> 'disabled',
			'help'				=> 'This feature will overwrite the \'Images per row\' setting.',
			'select-box-values' => array(
				'disabled'		=> 'Disabled',
				'2.4' 			=> 'Small: 2 Col, Big: 4 Col',
				'3.6' 			=> 'Small: 3 Col, Big: 6 Col',
				'4.8' 			=> 'Small: 4 Col, Big: 8 Col',
			),
		),
		'target' => array(
			'data-input-type' => 'switch',
			'switch-type'=> 'twoway',
			'title'		 => 'Lightbox',
			'size'		 => 'span2',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 => 'lightbox',
			'help'		 => 'To show a caption for your images in the lightbox please open the media library, click on the settings icon on your selected images and add a caption. You can customize the caption style in \'Customize -> Advanced\'',
			'switch-values' => array(
				'lightbox'	 => 'Yes',
				'no-lightbox'  => 'No',
			),
		),
	),
	'responsive_gutter_lg' => get_responsive_gutter('lg', true),
	'responsive_gutter_md' => get_responsive_gutter('md', true),
	'responsive_gutter_sm' => get_responsive_gutter('sm', true),
	'responsive_gutter_xs' => get_responsive_gutter('xs', true),
	'title_options' => array(
		'title'  	 => 'Title & Caption Visibility',
		'style-class' => 'ep-collapsed',
		'break'		 => '1,2',
		'data-hide-mobile' => true,
		'title_visibility' => array(
			'data-input-type' 	=> 'select-box',
			'title'		 		=> 'Visibility',
			'size'		 		=> 'span4',
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'default' 	 		=> 'hidden',
			'select-box-values' => array(
				'hidden'		=> 'Hide Both',
				'both' 			=> 'Show both title and caption',
				'title'			=> 'Show only title',
				'caption'		=> 'Show only caption',
			),
		),
		'title_position' => array(
			'data-input-type' 	=> 'select-box',
			'title'		 		=> 'Position',
			'size'		 		=> 'span2',
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'default' 	 		=> 'center',
			'select-box-values' => array(
				'center' 		=> 'Center',
				'left'			=> 	'Left',
				'right'			=> 'Right',
			),
		),
		'title_padding' => array(
			'title'			=> 'Padding',
			'help'			=> 'Padding has no effect if title position is set to \'Overlay Middle Center.\'',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 18,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			//'responsive'	=> true,
		),
	),
	'title_formatting' => array(
		'title'  	 => 'Title Formatting',
		'break'		 => '2,2',
		'data-hide-mobile' => true,
		'style-class' => 'ep-collapsed',
		'title_color' => array(
			'title'				=> 'Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'data-target'		=> '.spacer',
			'default'			=> 'transparent',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',	
		),
		'title_font' => array(
			'data-input-type' => 'select-fonts',
			'title'		 		=> 'Font Family',
			'size'		 		=> 'span2',
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'default' 	 		=> 'none',
			'select-box-values' => $fonts,
		),
		'title_fontsize' => array(
			'title'			=> 'Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 16,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			//'responsive'	=> true,
		),
		'title_text_transform' => array(
			'title'				=> 'Text Transform',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-box',
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'default'			=> 'none',
			'select-box-values' => array(
				'none'			=> 'None',
				'uppercase'		=> 'Uppercase',
			),
		),
	),
	'caption_formatting' => array(
		'title'  	 => 'Caption Formatting',
		'break'		 => '2,2,1',
		'data-hide-mobile' => true,
		'style-class' => 'ep-collapsed',
		'caption_color' => array(
			'title'				=> 'Color',
			'data-style-option' => true,
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'data-target'		=> '.spacer',
			'default'			=> 'transparent',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',	
		),
		'caption_font' => array(
			'data-input-type' => 'select-fonts',
			'title'		 		=> 'Font Family',
			'size'		 		=> 'span2',
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'default' 	 		=> 'none',
			'select-box-values' => $fonts,
		),
		'caption_fontsize' => array(
			'title'			=> 'Font Size',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 14,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			//'responsive'	=> true,
		),
		'caption_text_transform' => array(
			'title'				=> 'Text Transform',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-box',
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'default'			=> 'none',
			'select-box-values' => array(
				'none'			=> 'None',
				'uppercase'		=> 'Uppercase',
			),
		),
		'caption_padding_top' => array(
			'title'			=> 'Padding Top',
			'size'			=> 'span4',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 8,
			'min'			=> 0,
			'max'			=> 999,
			'class'				=> 'editor-listen',
			'data-handler'		=> 'save',
			'data-style-option' => true,
			'data-has-unit'	=> true,
			//'responsive'	=> true,
		),
	),
	'mouseover_options' => array(
		'title'  	 => 'Mouseover',
		'break'		 => '1,2',
		'data-hide-mobile' => true,
		'style-class'=> 'ep-collapsed',
		'mouseover' => array(
			'data-input-type' 	=> 'select-box',
			'title'		 		=> 'Effect',
			'size'		 		=> 'span4',
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
			'default' 	 		=> '3',
			'select-box-values' => array(
				'color'    => 'Color',
				'shadow'   => 'Shadow',
				'none'	   => 'None',
			),
		),
		'mouseover_color' => array(
			'title'			=> 'Color',
			'help'			=> 'Only applies for the color mouseover. Boxshadow is always black.',
			'size'			=> 'span2',
			'data-input-type'	=> 'color',
			'default'		=> 'transparent',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
		),
		'mouseover_opacity' => array(
			'title'			=> 'Opacity',
			'size'			=> 'span2',
			'offset'		=> false,
			'data-input-type' 	=> 'range-slider',
			'default'		=> 100,
			'min'			=> 0,
			'max'			=> 100,
			'class'      		=> 'editor-listen',
			'data-handler' 		=> 'save',
		),
	),
);

?>