<?php

// -----------------------------------------
// semplice
// admin/atts/modules/share.php
// -----------------------------------------

$share = array(
	'options' => array(
		'title'  	 => 'Type',
		'break'		 => '1',
		'data-hide-mobile' => true,
		'type' => array(
			'data-input-type' 			=> 'switch',
			'switch-type'				=> 'twoway',
			'title'		 				=> 'Type',
			'hide-title'				=> true,
			'size'		 				=> 'span4',
			'data-visibility-switch' 	=> true,
			'data-visibility-values' 	=> 'icons,buttons',
			'data-visibility-prefix'	=> 'ov-share',
			'default' 	 				=> 'icons',
			'class' 	 				=> 'editor-listen',
			'data-handler'				=> 'share',
			'switch-values' => array(
				'icons'  	=> 'Icons',
				'buttons'	=> 'Buttons',
			),
		),
	),
	'button-options' => array(
		'title'  	 => 'Colors',
		'break'		 => '3',
		'data-hide-mobile' => true,
		'style-class'		=> 'ov-share-buttons',
		'button_bg_color' => array(
			'title'				=> 'Button',
			'size'				=> 'span1',
			'data-input-type'	=> 'color',
			'default'			=> 'transparent',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'share',
			'data-target'		=> '.text',
			'data-css-attribute'=> 'background-color',
		),
		'button_border_color' => array(
			'title'				=> 'Border',
			'size'				=> 'span1',
			'data-input-type'	=> 'color',
			'default'			=> 'transparent',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'share',
			'data-target'		=> '.text',
			'data-css-attribute'=> 'border-color',
		),
		'button_text_color' => array(
			'title'				=> 'Text',
			'size'				=> 'span1',
			'data-input-type'	=> 'color',
			'default'			=> 'transparent',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'share',
			'data-target'		=> '.text',
			'data-css-attribute'=> 'color',
		),
	),
	'icon-options' => array(
		'title'  	 => 'Icons',
		'break'		 => '3',
		'data-hide-mobile' => true,
		'style-class' => 'ov-share-icons',
		'icon_color' => array(
			'title'				=> 'Color',
			'size'				=> 'span1',
			'data-input-type'	=> 'color',
			'default'			=> 'transparent',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'share',
			'data-target'		=> '.share-icon svg',
			'data-css-attribute'=> 'fill',
		),
		'icon_scale' => array(
			'title'				=> 'Scale',
			'size'				=> 'span1',
			'data-input-type' 	=> 'range-slider',
			'data-css-attribute'=> 'height',
			'data-target'		=> '.share-icon svg',
			'data-style-option' => true,
			'data-has-unit'		=> true,
			'default'			=> 26,
			'min'				=> 0,
			'max'				=> 9999,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'share',
			'data-range-slider' => 'share',
		),
		'icon_padding' => array(
			'title'				=> 'Padding',
			'size'				=> 'span1',
			'data-input-type' 	=> 'range-slider',
			'data-css-attribute'=> 'padding',
			'data-target'		=> '.share-icon a',
			'data-style-option' => true,
			'data-has-unit'		=> true,
			'default'			=> 10,
			'min'				=> 0,
			'max'				=> 9999,
			'style-class'		=> 'ov-share-icons',
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'share',
			'data-range-slider' => 'share',
		),
	),
	'icon-font-options' => array(
		'title'  	 => 'Title Formatting',
		'break'		 => '1,2,2',
		'style-class' => 'ep-collapsed ov-share-icons',
		'data-hide-mobile' => true,
		'icon_text_visibility' => array(
			'data-input-type' 	=> 'switch',
			'switch-type'		=> 'twoway',
			'title'		 		=> 'Visibility',
			'size'		 		=> 'span4',
			'default' 	 		=> 'visible',
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'share',
			'data-target'		=> '.share-icons-wrapper p',
			'switch-values' => array(
				'visible'		=> 'Visible',
				'hidden'		=> 'Hidden',
			),
		),
		'icon_text_color' => array(
			'title'				=> 'Color',
			'size'				=> 'span2',
			'data-input-type'	=> 'color',
			'default'			=> 'transparent',
			'class'				=> 'color-picker admin-listen-handler',
			'data-handler' 		=> 'colorPicker',
			'data-picker'		=> 'share',
			'data-target'		=> '.share-icons-wrapper p',
			'data-css-attribute'=> 'color',
		),
		'icon_font_family' => array(
			'title'				=> 'Font Family',
			'size'				=> 'span2',
			'data-input-type'	=> 'select-fonts',
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'share',
			'data-target'		=> '.share-icons-wrapper p',
			'select-box-values' => $fonts,
			'help'				=> 'No live preview available.',
		),
		'icon_font_size' => array(
			'title'				=> 'Font size',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'data-css-attribute'=> 'font-size',
			'data-target'		=> '.share-icons-wrapper p',
			'data-style-option' => true,
			'data-has-unit'		=> true,
			'default'			=> 14,
			'min'				=> 0,
			'max'				=> 9999,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'share',
			'data-range-slider' => 'share',
		),
		'icon_letter_spacing' => array(
			'title'				=> 'Letter Spacing',
			'size'				=> 'span2',
			'data-input-type' 	=> 'range-slider',
			'data-css-attribute'=> 'letter-spacing',
			'data-style-option' => true,
			'data-target'		=> '.share-icons-wrapper p',
			'data-has-unit'		=> true,
			'default'			=> 0,
			'min'				=> 0,
			'max'				=> 9999,
			'data-negative' 	=> true,
			'data-divider'		=> 10,
			'class' 	 		=> 'editor-listen',
			'data-handler'		=> 'share',
			'data-range-slider' => 'share',
		),
	),
);

?>